### ISSUE TITLE
Pretty finders

### ISSUE THREAD

**Issue by rastasheep** [shiroyasha/semaphore_api#1]
Let's create prettier finders instead of:

```
master = semaphore_api.branches.find { |branch| branch.name == "master" }
```

It would be great to have something like this:

```
master = semaphore_api.branches.find_by(:name => "master")
# or
dev      =  semaphore_api.branches.find("master")
```

Same thing with projects and branches ofc. :)

**Comment by shiroyasha** [comment]
#spijun_buba

**Comment by shiroyasha** [comment]
But I don't like that idea. It would be better to have an end-point for it, like GitHub has in their API.

And then we could simply:

``` rb
client.branch(project.hash_id, "master")
```

**Comment by shiroyasha** [comment]
But... maybe we could put a `find_by` matcher inside https://github.com/shiroyasha/zoid/blob/master/lib/zoid/resource.rb#L6.

That way you could automatically search by any field that is returned by the API.

**Comment by rastasheep** [comment]
:+1: that sounds great .. but it should be only defined on arrays..

**Comment by shiroyasha** [comment]
Done https://github.com/shiroyasha/zoid/pull/1

**Comment by shiroyasha** [comment]
Updated the README also https://github.com/shiroyasha/semaphore_api/blob/master/README.md#usage

**Comment by shiroyasha** [comment]
Closing
